project:
  type: datapage

website:
  title: "ManyBabies"
  navbar: false

format:
  datapage-html:
    theme: theme.scss
    mainfont: Open Sans
    title-block-banner: "#036C9A"
    title-block-banner-color: white
    grid:
      sidebar-width: 0px
      body-width: 800px
      margin-width: 0px

execute: 
  echo: false
  message: false
  warning: false
  error: false
