project:
  type: website

website:
  title: "ManyBabies"
  navbar:
    left:
      - href: index.qmd
        text: MB1

format:
  html:
    theme: [cosmo, styles.scss]
    fontsize: 1em
    toc: false

execute: 
  echo: false
  message: false
  warning: false
  error: false
